name: hufs_lecture_alarm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  provider: ^3.1.0
  firebase_messaging: ^5.1.4
  toast: ^0.1.5
  flutter_ringtone_player: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: '^0.7.2'

flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
